resolver: lts-12.19
packages:
  - .
  - ../planet-mitchell/planet-mitchell
extra-deps:
  - base-orphans-0.8
  - compact-0.1.0.1
  - compactable-0.1.2.2
  - deferred-folds-0.9.9.1
  - focus-1.0.1.2
  - free-5.1
  - list-transformer-1.0.4
  - monad-ste-0.1.0.0
  - multiset-0.3.4.1
  - network-2.8.0.0
  - nf-1.0.1.0
  - primitive-0.6.4.0
  - primitive-extras-0.7.1
  - reactive-banana-1.2.0.0
  - semigroupoids-5.3.1
  - semilattices-0.0.0.2
  - serialise-0.2.1.0
  - stm-containers-1.1.0.2
  - stm-hamt-1.2.0.2
  - strict-tuple-0.1.0
  - tagged-0.8.6
  - text-ansi-0.1.0
  - text-builder-0.6.4
  - unagi-chan-0.4.1.0
